# Generated by Django 4.0.1 on 2022-01-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_linkolympiads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkOlympiads',
        ),
    ]
