# Generated by Django 4.0.1 on 2022-01-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_linkolympiads'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='universities',
            field=models.ManyToManyField(to='universities.University'),
        ),
        migrations.DeleteModel(
            name='LinkOlympiads',
        ),
    ]
